# Generated by Django 2.2.19 on 2021-11-24 11:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20211124_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='category',
            field=models.TextField(default='', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2021, 11, 24, 14, 18, 23, 986335), verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2021, 11, 24, 14, 18, 23, 987335), verbose_name='Дата'),
        ),
    ]
