# Generated by Django 2.2.19 on 2021-11-27 11:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20211127_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2021, 11, 27, 14, 45, 34, 604428), verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2021, 11, 27, 14, 45, 34, 605424), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='category',
            field=models.CharField(choices=[('cat1', 'Фигурки'), ('cat2', 'Значки'), ('cat3', 'Постеры')], max_length=300, verbose_name='Категория'),
        ),
    ]
