# Generated by Django 2.2.19 on 2021-11-28 10:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20211127_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='isActive',
        ),
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('incart', 'В корзине'), ('intransit', 'Доставляется'), ('delivered', 'Доставлен')], default='delivered', max_length=300, verbose_name='Статус'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2021, 11, 28, 13, 26, 8, 54271), verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2021, 11, 28, 13, 26, 8, 54271), verbose_name='Дата'),
        ),
    ]
