# Generated by Django 2.2.19 on 2021-11-29 08:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20211128_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='total_price',
            field=models.IntegerField(default=0, verbose_name='Итоговая стоимость'),
        ),
        migrations.AddField(
            model_name='suborders',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Стоимость товаров'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2021, 11, 29, 11, 27, 5, 816948), verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2021, 11, 29, 11, 27, 5, 817947), verbose_name='Дата'),
        ),
    ]
