# Generated by Django 2.2.19 on 2021-12-01 07:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20211201_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2021, 12, 1, 10, 15, 26, 328906), verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2021, 12, 1, 10, 15, 26, 328906), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='category',
            field=models.CharField(choices=[('cat_1', 'Фигурки'), ('cat_2', 'Значки'), ('cat_3', 'Постеры')], max_length=300, verbose_name='Категория'),
        ),
    ]
